# Generated by scripts/generate_protocol_contract.py; do not edit.
# ruff: noqa
# fmt: off
MAX_INT = 2147483647
FIELDS = ('v', 'id', 'mutation', 'value', 'duration', 'telegraph', 'at')
REGISTRY = {'ambient': (1, 100, 1), 'ward_efficacy': (4, 80, 2), 'hunger_rate': (3, 90, 3)}
MUTATIONS = {'ambient': {'symbol': 'CHAOS_AMBIENT',
             'id': 0,
             'name': 'ambient',
             'cost': 1,
             'value': [1, 3],
             'duration': [0, 0],
             'telegraph': 1,
             'engine_sanity_max': None,
             'director_sanity_max': 100,
             'ordinary_food': False,
             'persistent': False,
             'rule': 'none'},
 'ward_efficacy': {'symbol': 'CHAOS_WARD',
                   'id': 1,
                   'name': 'ward_efficacy',
                   'cost': 4,
                   'value': [50, 50],
                   'duration': [1, 50],
                   'telegraph': 2,
                   'engine_sanity_max': 80,
                   'director_sanity_max': 80,
                   'ordinary_food': False,
                   'persistent': True,
                   'rule': 'halve'},
 'hunger_rate': {'symbol': 'CHAOS_HUNGER',
                 'id': 2,
                 'name': 'hunger_rate',
                 'cost': 3,
                 'value': [2, 2],
                 'duration': [1, 50],
                 'telegraph': 3,
                 'engine_sanity_max': 90,
                 'director_sanity_max': 90,
                 'ordinary_food': True,
                 'persistent': True,
                 'rule': 'double'}}
EVENTS = frozenset(('eat',
 'read',
 'zap',
 'apply',
 'pray',
 'kill',
 'level_enter',
 'level_leave',
 'sanity',
 'insight',
 'death',
 'sleep',
 'session',
 'safe_point',
 'ack',
 'telegraph',
 'expiry',
 'haunting',
 'haunt_step',
 'backtrack',
 'curio'))
REASONS = frozenset(('ok',
 'schema',
 'oversize',
 'duplicate',
 'schedule',
 'budget',
 'active',
 'ineligible',
 'log_failure'))
VITALS = ('hp', 'hp_max', 'power', 'power_max')
NUMBERS = ('v',
 'seq',
 'turn',
 'safe',
 'sanity',
 'insight',
 'budget',
 'spent',
 'reserved',
 'last_id')
REQUEST_BOUNDS = {'v': (1, 1),
 'id': (1, 2147483647),
 'value': (0, 2147483647),
 'duration': (0, 2147483647),
 'telegraph': (0, 2147483647),
 'at': (1, 2147483647)}
EVENT_BOUNDS = {'v': (1, 1),
 'seq': (1, 2147483647),
 'turn': (0, 2147483647),
 'safe': (0, 2147483647),
 'sanity': (0, 100),
 'insight': (0, 2147483647),
 'budget': (0, 12),
 'spent': (0, 12),
 'reserved': (0, 12),
 'last_id': (0, 2147483647)}
VITAL_BOUNDS = {'hp': (0, 2147483647),
 'hp_max': (0, 2147483647),
 'power': (-2147483647, 2147483647),
 'power_max': (0, 2147483647)}
REQUEST_CAP = 512
EVENT_CAP = 4096
DETAIL_CAP = 256
PHASES = ('attempt', 'result')
ACK_STATUSES = ('accepted', 'rejected')
ACK_NUMBERS = ('id', 'value', 'duration', 'telegraph', 'at', 'cost', 'expires')
ACK_BOUNDS = (0, 2147483647)
REQUEST_VERSION = 1
EVENT_VERSION = 1
