/* NetHack General Public License - bounded, engine-independent protocol v1. */
#ifndef CHAOS_PROTOCOL_H
#define CHAOS_PROTOCOL_H
#include <stddef.h>
/* BEGIN GENERATED PROTOCOL CONTRACT */
/* Generated by scripts/generate_protocol_contract.py; do not edit. */
#define CHAOS_MAX_REQUEST 512
#define CHAOS_STATE_VERSION 2
#define CHAOS_OBSERVATION_VERSION 4
#define CHAOS_REQUEST_VERSION 1
#define CHAOS_EVENT_VERSION 3
#define CHAOS_MAX_INT 2147483647
#define CHAOS_MAX_COUNTER 2147483647L
#define CHAOS_REQUEST_STRING_BUFFER 24
#define CHAOS_TURN_HEADROOM 50
#define CHAOS_COSMETIC_LIMIT 3
#define CHAOS_COSMETIC_SPACING 50
#define CHAOS_COSMETIC_MASK 7
#define CHAOS_COSMETIC_POLICY 2
#define CHAOS_BUDGET_SANITY_MIN 0
#define CHAOS_BUDGET_SANITY_MAX 100
#define CHAOS_BUDGET_BASE 2
#define CHAOS_BUDGET_STEP 10
#define CHAOS_BUDGET_CEILING 12
#define CHAOS_SPEND_CURIO 1
#define CHAOS_COST_CURIO 1
#define CHAOS_SPEND_HAUNT 2
#define CHAOS_COST_HAUNT 2
enum chaos_kind { CHAOS_AMBIENT = 0, CHAOS_WARD = 1, CHAOS_HUNGER = 2, CHAOS_KINDS = 3 };
enum chaos_result { CHAOS_OK = 0, CHAOS_SCHEMA = 1, CHAOS_OVERSIZE = 2, CHAOS_DUPLICATE = 3, CHAOS_SCHEDULE = 4, CHAOS_BUDGET = 5, CHAOS_ACTIVE = 6, CHAOS_INELIGIBLE = 7, CHAOS_LOG_FAILURE = 8, CHAOS_FUTURE = 9, CHAOS_COSMETIC_BUDGET = 10, CHAOS_COSMETIC_COOLDOWN = 11, CHAOS_COSMETIC_REPEAT = 12 };
enum chaos_contract_rule { CHAOS_RULE_NONE, CHAOS_RULE_HALVE, CHAOS_RULE_DOUBLE };
#define CHAOS_MUTATION_ROWS(X) \
    X(CHAOS_AMBIENT, "ambient", 0, 1, 1, 3, 0, 0, 1, -1, 0, 0, CHAOS_RULE_NONE) \
    X(CHAOS_WARD, "ward_efficacy", 4, 0, 50, 50, 1, 50, 2, 80, 0, 1, CHAOS_RULE_HALVE) \
    X(CHAOS_HUNGER, "hunger_rate", 3, 0, 2, 2, 1, 50, 3, 90, 1, 1, CHAOS_RULE_DOUBLE)

#define CHAOS_RESULT_ROWS(X) \
    X(CHAOS_OK, "ok", 1) \
    X(CHAOS_SCHEMA, "schema", 1) \
    X(CHAOS_OVERSIZE, "oversize", 1) \
    X(CHAOS_DUPLICATE, "duplicate", 1) \
    X(CHAOS_SCHEDULE, "schedule", 1) \
    X(CHAOS_BUDGET, "budget", 1) \
    X(CHAOS_ACTIVE, "active", 1) \
    X(CHAOS_INELIGIBLE, "ineligible", 1) \
    X(CHAOS_LOG_FAILURE, "log_failure", 1) \
    X(CHAOS_FUTURE, "future", 0) \
    X(CHAOS_COSMETIC_BUDGET, "cosmetic_budget", 1) \
    X(CHAOS_COSMETIC_COOLDOWN, "cosmetic_cooldown", 1) \
    X(CHAOS_COSMETIC_REPEAT, "cosmetic_repeat", 1)

#define CHAOS_SIGNAL_ROWS(X) \
    X(1, "A distant whisper brushes against your thoughts.") \
    X(2, "The lines of your wards seem thin and uncertain.") \
    X(3, "An unnatural hunger coils in your stomach.")

#define CHAOS_SIGNAL_COUNT 3
#define CHAOS_AMBIENT_MESSAGE_ROWS(X) \
    X(1, "The shadows lean closer.") \
    X(2, "Something beyond the walls listens.") \
    X(3, "For a moment, silence has teeth.")

#define CHAOS_AMBIENT_MESSAGE_COUNT 3
#define CHAOS_FIELD_COUNT 7
#define CHAOS_FIELD_MASK 127
#define CHAOS_FIELD_NAMES "v", "id", "mutation", "value", "duration", "telegraph", "at"
#define CHAOS_MUTATION_FIELD 2
#define CHAOS_ASSIGN_FIELDS(r, f) \
    (r)->v = (f)[0]; \
    (r)->id = (f)[1]; \
    (r)->kind = (f)[2]; \
    (r)->value = (f)[3]; \
    (r)->duration = (f)[4]; \
    (r)->telegraph = (f)[5]; \
    (r)->at = (f)[6];

#define CHAOS_VALIDATE_FIELDS(r) \
    if ((r)->v < 1 || (r)->v > 1) return 0; \
    if ((r)->id < 1 || (r)->id > 2147483647) return 0; \
    if ((r)->value < 0 || (r)->value > 2147483647) return 0; \
    if ((r)->duration < 0 || (r)->duration > 2147483647) return 0; \
    if ((r)->telegraph < 0 || (r)->telegraph > 2147483647) return 0; \
    if ((r)->at < 1 || (r)->at > 2147483647) return 0;

#define CHAOS_EVENT_EAT "eat"
#define CHAOS_EVENT_READ "read"
#define CHAOS_EVENT_ZAP "zap"
#define CHAOS_EVENT_APPLY "apply"
#define CHAOS_EVENT_PRAY "pray"
#define CHAOS_EVENT_KILL "kill"
#define CHAOS_EVENT_LEVEL_ENTER "level_enter"
#define CHAOS_EVENT_LEVEL_LEAVE "level_leave"
#define CHAOS_EVENT_SANITY "sanity"
#define CHAOS_EVENT_INSIGHT "insight"
#define CHAOS_EVENT_DEATH "death"
#define CHAOS_EVENT_SLEEP "sleep"
#define CHAOS_EVENT_SESSION "session"
#define CHAOS_EVENT_SAFE_POINT "safe_point"
#define CHAOS_EVENT_ACK "ack"
#define CHAOS_EVENT_TELEGRAPH "telegraph"
#define CHAOS_EVENT_EXPIRY "expiry"
#define CHAOS_EVENT_HAUNTING "haunting"
#define CHAOS_EVENT_HAUNT_STEP "haunt_step"
#define CHAOS_EVENT_BACKTRACK "backtrack"
#define CHAOS_EVENT_CURIO "curio"
#define CHAOS_PHASE_ATTEMPT "attempt"
#define CHAOS_PHASE_RESULT "result"
#define CHAOS_STATUS_ACCEPTED "accepted"
#define CHAOS_STATUS_REJECTED "rejected"
#define CHAOS_STATUS_ADMITTED "admitted"
#define CHAOS_EVENT_FORMAT "{\"v\":%d,\"seq\":%ld,\"turn\":%ld,\"safe\":%ld,\"event\":%s,\"phase\":%s,\"detail\":%s,\"sanity\":%d,\"insight\":%d,\"budget\":%d,\"spent\":%d,\"reserved\":%d,\"last_id\":%d,\"vitals\":{\"hp\":%d,\"hp_max\":%d,\"power\":%d,\"power_max\":%d},\"cosmetic\":{\"seen\":%d,\"last_turn\":%ld}%s}\n"
#define CHAOS_ACK_FORMAT ",\"id\":%d,\"status\":\"%s\",\"mutation\":\"%s\",\"value\":%d,\"duration\":%d,\"telegraph\":%d,\"at\":%d,\"cost\":%d,\"cosmetic_cost\":%d,\"expires\":%ld"
#define CHAOS_JOURNAL_FORMAT "{\"v\":1,\"policy\":2,\"turn\":%ld,\"safe\":%ld%s}\n"
enum chaos_observation_operation { CHAOS_OBS_OP_NONE = 0, CHAOS_OBS_OP_WHISTLING = 1, CHAOS_OBS_OP_FOUNTAIN_DRINK = 2, CHAOS_OBS_OP_WHISTLE_ATTENTION = 3 };
enum chaos_observation_stage { CHAOS_OBS_STAGE_ENABLED = 0, CHAOS_OBS_STAGE_STARTED = 1, CHAOS_OBS_STAGE_NOTICE = 2, CHAOS_OBS_STAGE_COMPLETED = 3, CHAOS_OBS_STAGE_BLOCKED = 4 };
enum chaos_observation_fact { CHAOS_OBS_FACT_NONE = 0, CHAOS_OBS_FACT_SOUND_HIGH = 1, CHAOS_OBS_FACT_SOUND_SHRILL = 2, CHAOS_OBS_FACT_SOUND_NORMAL = 3, CHAOS_OBS_FACT_SOUND_STRANGE = 4, CHAOS_OBS_FACT_SOUND_HUMMING = 5, CHAOS_OBS_FACT_WATER_REFRESHED = 6, CHAOS_OBS_FACT_WATER_FOUL = 7, CHAOS_OBS_FACT_CANNOT_REACH = 8, CHAOS_OBS_FACT_DETECTION_PRESENTED = 9, CHAOS_OBS_FACT_ATTENTION = 10 };
enum chaos_obs_channel { CHAOS_OBS_CHANNEL_MESSAGE = 1, CHAOS_OBS_CHANNEL_MAP = 2 };
enum chaos_obs_role { CHAOS_OBS_ROLE_ENABLE, CHAOS_OBS_ROLE_START, CHAOS_OBS_ROLE_NOTICE, CHAOS_OBS_ROLE_COMPLETE, CHAOS_OBS_ROLE_BLOCK };
#define CHAOS_OBS_FAMILY_ROWS(X) \
    X(CHAOS_OBS_OP_WHISTLING, 0, "whistling") \
    X(CHAOS_OBS_OP_FOUNTAIN_DRINK, 1, "fountain_drink") \
    X(CHAOS_OBS_OP_WHISTLE_ATTENTION, 1, "whistle_attention")

#define CHAOS_OBS_FACT_ROWS(X) \
    X(CHAOS_OBS_FACT_SOUND_HIGH, 1, CHAOS_OBS_CHANNEL_MESSAGE, 0, "sound_high") \
    X(CHAOS_OBS_FACT_SOUND_SHRILL, 1, CHAOS_OBS_CHANNEL_MESSAGE, 0, "sound_shrill") \
    X(CHAOS_OBS_FACT_SOUND_NORMAL, 1, CHAOS_OBS_CHANNEL_MESSAGE, 0, "sound_normal") \
    X(CHAOS_OBS_FACT_SOUND_STRANGE, 1, CHAOS_OBS_CHANNEL_MESSAGE, 0, "sound_strange") \
    X(CHAOS_OBS_FACT_SOUND_HUMMING, 1, CHAOS_OBS_CHANNEL_MESSAGE, 0, "sound_humming") \
    X(CHAOS_OBS_FACT_WATER_REFRESHED, 2, CHAOS_OBS_CHANNEL_MESSAGE, 0, "water_refreshed") \
    X(CHAOS_OBS_FACT_WATER_FOUL, 2, CHAOS_OBS_CHANNEL_MESSAGE, 0, "water_foul") \
    X(CHAOS_OBS_FACT_CANNOT_REACH, 2, CHAOS_OBS_CHANNEL_MESSAGE, 1, "cannot_reach") \
    X(CHAOS_OBS_FACT_DETECTION_PRESENTED, 2, CHAOS_OBS_CHANNEL_MAP, 0, "detection_presented") \
    X(CHAOS_OBS_FACT_ATTENTION, 3, CHAOS_OBS_CHANNEL_MESSAGE, 0, "attention")

#define CHAOS_OBS_STAGE_ROWS(X) \
    X(CHAOS_OBS_STAGE_ENABLED, CHAOS_OBS_ROLE_ENABLE, "enabled", "result") \
    X(CHAOS_OBS_STAGE_STARTED, CHAOS_OBS_ROLE_START, "started", "attempt") \
    X(CHAOS_OBS_STAGE_NOTICE, CHAOS_OBS_ROLE_NOTICE, "notice", "result") \
    X(CHAOS_OBS_STAGE_COMPLETED, CHAOS_OBS_ROLE_COMPLETE, "completed", "result") \
    X(CHAOS_OBS_STAGE_BLOCKED, CHAOS_OBS_ROLE_BLOCK, "blocked", "result")

/* END GENERATED PROTOCOL CONTRACT */
/* Read-only metadata, not persistent state or root authenticity. */
struct chaos_obs_family_info { int id, allow_blocked; const char *name; };
struct chaos_obs_fact_info { int id, operation, channel, implies_blocked; const char *name; };
struct chaos_obs_stage_info { int id, role; const char *name, *phase; };
const struct chaos_obs_family_info *chaos_obs_family(int);
const struct chaos_obs_fact_info *chaos_obs_fact(int, int);
const struct chaos_obs_stage_info *chaos_obs_stage(int);
const char *chaos_obs_operation_name(int);
const char *chaos_obs_fact_name(int);
int chaos_obs_row_valid(int, int, long, long, int);

struct chaos_request { int v, id, kind, value, duration, telegraph, at; };
struct chaos_effect { int value, cost; long expires; };
struct chaos_state {
    int version, spent, reserved, last_id;
    long seq, safe;
    struct chaos_effect effects[CHAOS_KINDS];
    int cosmetic_seen;
    long cosmetic_last_turn;
};
int chaos_parse(const char *, size_t, struct chaos_request *);
const char *chaos_reason(int);
const char *chaos_name(int);
int chaos_cost(int);
int chaos_cosmetic_cost(int);
int chaos_quote(char *, size_t, const char *, size_t);
void chaos_state_init(struct chaos_state *);
int chaos_state_valid(const struct chaos_state *);
int chaos_budget(const struct chaos_state *, int);
/* Fixed-price lifetime debit: only spent changes; failures leave state intact. */
int chaos_spend_non_effect(struct chaos_state *, int, int);
void chaos_expire(struct chaos_state *, long);
/* eligibility: 0 unconscious/dead, 1 ordinary food, 2 conscious non-food. */
int chaos_admit(struct chaos_state *, const struct chaos_request *, long, int, int);
int chaos_rule(const struct chaos_state *, int, long, int);
#endif
